select
    world_scan_id,
    ingested_at_utc,
    scan_scope,
    tile_key,
    x1,
    y1,
    x2,
    y2,
    coords,
    x,
    y,
    coord_key,
    trim(state) as state,
    level,
    trim(status) as status,
    distance,
    trim(castle) as castle_name,
    trim(owner) as owner_name,
    trim(owner_key) as owner_key,
    trim(alliance) as alliance_name,
    trim(alliance_key) as alliance_key,
    prestige,
    honor
from raw.bronze_world_scan_rows